try {
  throw new Error()
} catch (error) {}
